### PR TITLE
Transpile to ES5

### LINKED ISSUE #23: Support for older browsers
I've had some troubles using daggy on older browsers (e.g. IE, Safari 8), which I believe is due to the  usage of ES6 features (`const` etc). If I manually transpile the code using a transpiler such as e.g. `babel`, everything works fine.

I'm not very well versed in what the best practices are for publishing `npm` packages, but I'm thinking it might be a good idea to transpile before publishing? See e.g. http://jamesknelson.com/writing-npm-packages-with-es6-using-the-babel-6-cli/

Is this something you've considered?

### PR DESCRIPTION
**Pull request by eahlberg**
This implements transpiling from ES6 source code to ES5 compatible code using [Babel](http://babeljs.io/) to resolve #23.

### CODE REVIEW

**Comment by eahlberg** [comment]
In general, what's your thoughts on testing these changes? I've tested it manually in my own application, but that's not a very rigorous approach.

There are two things I considered adding, but skipped:
- Currently, the module is not exported using CommonJS syntax (see [here](https://github.com/fantasyland/daggy/blob/master/src/daggy.js#L154-L157)). If you would change  this to ES6 syntax, I think [this](https://github.com/59naga/babel-plugin-add-module-exports) might be needed.
- It might be convenient to have a `prepublish` script in `package.json` as mentioned [here](http://jamesknelson.com/writing-npm-packages-with-es6-using-the-babel-6-cli/), but I figured that's your call.

**Comment by davidchambers** [comment]
Thanks for the pull request, @eahlberg. We could adopt this approach, but to simplify maintenance and distribution I would prefer to rewrite the source code in ES3 syntax. Let me know whether #25 addresses your needs.

**Comment by eahlberg** [comment]
No problem. Thank you for providing the library!

Ok, I see. #25 definitely addresses my needs and I have no opinion on transpiling vs rewriting!

**Comment by davidchambers** [comment]
Okay. I'll leave this pull request open for the time being. If and when #25 is merged I'll close this pull request and publish a new version of daggy.

**Comment by davidchambers** [comment]
The [v1.2.0 release][1] runs in ES5 environments, so I'll close this pull request.


[1]: https://github.com/fantasyland/daggy/releases/tag/v1.2.0

**Pull request closed without merging**
