### PR TITLE
Change sanctuary-type-classes to sanctuary-show

### PR DESCRIPTION
**Pull request by santanaG**
All done!

### CODE REVIEW

**Comment by davidchambers** [comment]
Looking good! All that is missing now are assertions for `show(tpl)` and `show(list)`. :)

**Comment by santanaG** [comment]
Should tests also be made for unit variants(Nil) and the constructor(Cons)?

**Comment by davidchambers** [comment]
Adding a test case for `show(List.Nil)` is a good idea. I suggest leaving the behaviour of `show(List.Cons)` undefined.

**Comment by santanaG** [comment]
One last question. I also noticed that show(List) is a thing. Should that also be left undefined?

**Comment by davidchambers** [comment]
> Should that also be left undefined?

Yes. I believe so.

**Comment by davidchambers** [comment]
Please squash one last time. :)

**Pull request merged**
